name: Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.astro'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.md'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Lint and check formatting
        run: pnpm run lint
